[project]
name = "data-agents"
version = "0.1.0"
description = "Prototype for general data agents following the env-agents structure"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.13.3",
]
